Repository PeopleForBikes/PeopleForBikes.github.io, pull requests merged in 2022-01, with the labels that each got.

#6 Fix font issues
  .gitignore
  justfile
  sass/_custom.scss
  static/fonts/DharmaGothicE-ExBold.otf
  static/fonts/DharmaGothicE-ExLight.otf
  templates/_variables.html
  templates/index.html
  themes/juice/sass/_custom.scss
  themes/juice/sass/_custom_fonts.scss
  themes/juice/sass/_text.scss
  themes/juice/sass/juice.scss
  themes/juice/templates/_variables.html
  themes/juice/templates/index.html
Labels: size/XL

#8 Adds favicon
  static/android-chrome-192x192.png
  static/android-chrome-512x512.png
  static/apple-touch-icon.png
  static/browserconfig.xml
  static/favicon-16x16.png
  static/favicon-32x32.png
  static/favicon.ico
  static/safari-pinned-tab.svg
  static/site.webmanifest
  templates/index.html
Labels: size/M

#11 Add missing GitHub templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/help_request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: size/L

#13 Improve content
  content/_index.md
  templates/index.html
  themes/juice/sass/_custom.scss
  themes/juice/templates/index.html
Labels: size/S
